# 在 GitHub Actions 页面显示的流水线名字
name: Build Push and Deploy

# 触发条件:push 到 main 时触发;向 main 提 pull request 时也触发.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

# 镜像名，统一定义
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ml-cicd-demo

# GitHub 会分配一台临时 Ubuntu runner 来执行流水线
jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    # 按步骤执行：拉取代码到GitHub runner，安装依赖，训练模型，运行测试，登录 GitHub Container Registry，构建并推送 Docker 镜像
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert image name to lowercase
        run: echo "IMAGE_NAME_LOWER=${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train demo model
        run: |
          python train/train.py

      - name: Run tests
        run: |
          pytest -v

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME_LOWER }}:main
            ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}
  deploy:
    needs: build-and-push
    if: github.event_name == 'push'
    runs-on: [self-hosted, linux, x64, ml-cd]

    steps:
      - name: Deploy with local script
        run: |
          cd ~/projects/ml-cicd-demo
          git fetch origin main
          git reset --hard origin/main
          ./scripts/deploy_compose.sh
